require('plugins.cmp')
require('plugins.colorscheme')
require('plugins.autopairs')
require('plugins.lspconfig')
-- require('plugins.telescope')
require('plugins.fzf')
require('plugins.treesitter')
require('plugins.harpoon')
require('plugins.lualine')
require('plugins.markdown')
require('plugins.lazygit')
require('plugins.oil')
require('base')
require('keymaps')
require('vim._core.ui2').enable({})
